import { test, expect, openApp, reloadApp, gotoPage, createPage, doc, para, wsEval, uiEval, pageIdByTitle, editorOf, MOD } from './fixtures'

test.describe('navigation', () => {
  test('browser back / forward walk through visited pages', async ({ page }) => {
    await openApp(page)
    const wiki = await pageIdByTitle(page, 'Team wiki')
    const reading = await pageIdByTitle(page, 'Reading list')
    await page.locator('.sb section[aria-label="Pages"] .sb-row__link', { hasText: 'Team wiki' }).click()
    await expect(page.locator('#main .pv-title')).toHaveValue('Team wiki')
    await page.locator('.sb section[aria-label="Pages"] .sb-row__link', { hasText: 'Reading list' }).click()
    await expect(page.locator('#main .pv-title')).toHaveValue('Reading list')
    await page.goBack()
    await expect(page).toHaveURL(new RegExp(`#/p/${wiki}$`))
    await expect(page.locator('#main .pv-title')).toHaveValue('Team wiki')
    await page.goForward()
    await expect(page).toHaveURL(new RegExp(`#/p/${reading}$`))
    await expect(page.locator('#main .pv-title')).toHaveValue('Reading list')
  })

  test('the palette returns focus to the editor after Escape', async ({ page }) => {
    await openApp(page)
    const id = await createPage(page, { title: 'Focus return', content: doc(para('caret lives here')) })
    await gotoPage(page, id)
    const ed = editorOf(page, id)
    await ed.locator('p').first().click()
    await page.keyboard.press('End')
    await expect(ed).toBeFocused()
    await page.waitForTimeout(150)
    await page.keyboard.press(`${MOD}+k`)
    await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(ed).toBeFocused()
    // a human-scale pause before typing on (ProseMirror re-syncs its selection shortly after focus)
    await page.waitForTimeout(150)
    await page.keyboard.type(' still typing')
    await expect(ed).toContainText('caret lives here still typing')
  })

  // regression: focus given back with a plain focus() put the caret at the start when the last click
  // in the editor was under 300 ms ago (ProseMirror then trusts the browser's reset) — quick hands lost it
  test('the palette and dialogs give the editor its caret back, even right after a click', async ({ page }) => {
    await openApp(page)
    const id = await createPage(page, { title: 'Quick hands', content: doc(para('caret lives here')) })
    await gotoPage(page, id)
    const ed = editorOf(page, id)
    await ed.locator('p').first().click()
    await page.keyboard.press('End')
    await expect(ed).toBeFocused()
    await page.keyboard.press(`${MOD}+k`)
    await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(ed).toBeFocused()
    await page.keyboard.type(' A')
    await expect(ed).toContainText('caret lives here A')
    // a dialog with a field does the same ("Move to", opened right from the editor)
    await ed.locator('p').first().click()
    await page.keyboard.press('End')
    await uiEval(page, (s, pageId) => s.openModal({ type: 'move', pageId }), id)
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(ed).toBeFocused()
    await page.keyboard.type(' B')
    await expect(ed).toContainText('caret lives here A B')
  })

  test('start page setting and collapsed sidebar survive a reload', async ({ page }) => {
    await openApp(page)
    await page.keyboard.press(`${MOD}+,`)
    const dialog = page.getByRole('dialog')
    const wiki = await pageIdByTitle(page, 'Team wiki')
    await dialog.locator('select').first().selectOption(wiki)
    expect(await wsEval(page, (s) => s.settings.startPageId)).toBe(wiki)
    await page.keyboard.press('Escape')
    await page.keyboard.press(`${MOD}+\\`)
    await expect(page.locator('aside.sb')).toHaveAttribute('data-state', 'collapsed')
    await page.evaluate(() => (window.location.hash = '#/'))
    await reloadApp(page)
    await expect(page.locator('#main .pv-title')).toHaveValue('Team wiki')
    await expect(page.locator('aside.sb')).toHaveAttribute('data-state', 'collapsed')
  })
})

test.describe('database rows and columns', () => {
  test('delete a row from its context menu, then undo', async ({ page }) => {
    await openApp(page)
    const projects = await pageIdByTitle(page, 'Projects')
    await gotoPage(page, projects)
    const dbEl = page.locator('#main section.db').first()
    await dbEl.getByRole('tab').filter({ hasText: 'All projects' }).click()
    const row = dbEl.locator('.dbt-row[role="row"]', { has: page.locator('.dbt-cell--title', { hasText: 'Brand refresh' }) })
    await row.click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Delete' }).click()
    await expect(row).toHaveCount(0)
    await expect(page.getByText('Row moved to trash')).toBeVisible()
    await expect(dbEl.locator('.db-counter__num')).toHaveText('7')
    await page.getByRole('button', { name: 'Undo' }).click()
    await expect(dbEl.locator('.dbt-row[role="row"]', { has: page.locator('.dbt-cell--title', { hasText: 'Brand refresh' }) })).toBeVisible()
    await expect(dbEl.locator('.db-counter__num')).toHaveText('8')
  })

  test('add a checkbox property and tick a cell', async ({ page }) => {
    await openApp(page)
    const reading = await pageIdByTitle(page, 'Reading list')
    await gotoPage(page, reading)
    const dbEl = page.locator('#main section.db').first()
    await dbEl.getByRole('tab').filter({ hasText: 'Table' }).click()
    await dbEl.locator('.dbt-hcell--add button').click()
    await page.getByRole('menuitem', { name: /^Checkbox/ }).click()
    // the property menu opens for naming — confirm with Escape
    await page.keyboard.press('Escape')
    const prop = await wsEval(page, (s, id) => s.databases[id].properties.find((p: { type: string }) => p.type === 'checkbox') ?? null, reading)
    expect(prop).not.toBeNull()
    const row = dbEl.locator('.dbt-row[role="row"]', { has: page.locator('.dbt-cell--title', { hasText: 'Shape Up' }) })
    await row.locator('[role="gridcell"][data-type="checkbox"]').click()
    await expect
      .poll(() => wsEval(page, (s, { id, pid }) => (Object.values(s.pages) as Array<Record<string, any>>).find((p) => p.databaseId === id && p.title === 'Shape Up')?.properties[pid], { id: reading, pid: prop.id }))
      .toBe(true)
  })

  test('search rows from the database toolbar', async ({ page }) => {
    await openApp(page)
    const projects = await pageIdByTitle(page, 'Projects')
    await gotoPage(page, projects)
    const dbEl = page.locator('#main section.db').first()
    await dbEl.getByRole('tab').filter({ hasText: 'All projects' }).click()
    await dbEl.getByRole('toolbar', { name: 'Database toolbar' }).getByRole('button', { name: 'Search' }).click()
    // a title no relation points at (Parent item / Blocked by values are searchable too)
    await page.getByPlaceholder('Search rows…').fill('lead-routing')
    await expect(dbEl.locator('.dbt-body .dbt-row[role="row"]')).toHaveCount(1)
    await expect(dbEl.locator('.db-counter__num')).toHaveText('1/8')
  })
})
