/**
 * Pixel-art icons for the 1997 spreadsheet chrome. Each icon is a character map
 * (one char = one pixel) rendered to an inline SVG made of horizontal runs.
 * Colours are set as SVG attributes (not CSS) so html2canvas renders them exactly.
 */

const PAL: Record<string, string> = {
  k: '#000000',
  w: '#ffffff',
  l: '#c0c0c0',
  g: '#808080',
  y: '#ffff00',
  o: '#808000',
  n: '#000080',
  b: '#0000ff',
  c: '#00ffff',
  t: '#008080',
  r: '#ff0000',
  m: '#800000',
  e: '#008000',
  G: '#00ff00',
  p: '#800080',
}

function pixelSvg(map: string[], scale = 1): string {
  const h = map.length
  const w = Math.max(...map.map((r) => r.length))
  let rects = ''
  for (let y = 0; y < h; y++) {
    const row = map[y]
    let x = 0
    while (x < row.length) {
      const ch = row[x]
      if (ch === '.' || ch === ' ' || !PAL[ch]) {
        x++
        continue
      }
      let run = 1
      while (x + run < row.length && row[x + run] === ch) run++
      rects += `<rect x="${x}" y="${y}" width="${run}" height="1" fill="${PAL[ch]}"/>`
      x += run
    }
  }
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w * scale}" height="${h * scale}" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`
}

const MAPS: Record<string, string[]> = {
  sheet: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kttttttttttttk.',
    '.kwwgwwwgwwwgwk.',
    '.kggggggggggggk.',
    '.kwwgwwwgwwwgwk.',
    '.kggggggggggggk.',
    '.kwwgwwwgwwrgwk.',
    '.kggggggggrrggk.',
    '.kwwgwbbgwrrgwk.',
    '.kgggbbgggrrggk.',
    '.kwwgbbwgrrrgwk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  new: [
    '................',
    '...kkkkkkk......',
    '...kwwwwwkk.....',
    '...kwwwwwkwk....',
    '...kwwwwwkkkk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  open: [
    '................',
    '................',
    '.kkkkk..........',
    'kowwwok.........',
    'kowooookkkkkkk..',
    'koooooooooooook.',
    'kooookkkkkkkkkkk',
    'koookyyyyyyyyyyk',
    'koookyyyyyyyyyk.',
    'kookyyyyyyyyyyk.',
    'kookyyyyyyyyyk..',
    'kokyyyyyyyyyyk..',
    'kokyyyyyyyyyk...',
    'kkyyyyyyyyyyk...',
    'kkkkkkkkkkkk....',
    '................',
  ],
  save: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.knwwwwwwwwwwnk.',
    '.knwwwwwwwwwwnk.',
    '.knwggggggggwnk.',
    '.knwwwwwwwwwwnk.',
    '.knwggggggggwnk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnnnnk.',
    '.knnllllllllnnk.',
    '.knnlnnlllllnnk.',
    '.knnlnnlllllnnk.',
    '.knnlnnlllllnnk.',
    '.knnllllllllnnk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  print: [
    '................',
    '....kkkkkkkk....',
    '....kwwwwwwk....',
    '....kwkkkkwk....',
    '....kwwwwwwk....',
    '....kwkkkwwk....',
    '..kkkkkkkkkkkk..',
    '.kllllllllllllk.',
    '.kwwwwwwwwwwwlk.',
    '.kllllllllllGlk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    '..kwwwwwwwwwwk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  preview: [
    '................',
    '.kkkkkkkk.......',
    '.kwwwwwwkk......',
    '.kwkkkkwkwk.....',
    '.kwwwwwwwkkk....',
    '.kwkkkkkkkwk....',
    '.kwwwwkkkkk.....',
    '.kwkkkkcccck....',
    '.kwwwkcwcccck...',
    '.kwkkkcwcccck...',
    '.kwwwkcccccck...',
    '.kkkkkkcccckk...',
    '.......kkkkkkk..',
    '............kkk.',
    '.............kk.',
    '................',
  ],
  spell: [
    '................',
    '..k...kkk...kk..',
    '.k.k..k..k.k..k.',
    '.kkk..kkk..k....',
    '.k.k..k..k.k..k.',
    '.k.k..kkk...kk..',
    '................',
    '............e...',
    '...........ee...',
    '..........ee....',
    '..e......ee.....',
    '..ee....ee......',
    '...ee..ee.......',
    '....eeee........',
    '.....ee.........',
    '................',
  ],
  cut: [
    '................',
    '....k.....k.....',
    '....k.....k.....',
    '....kk...kk.....',
    '.....k...k......',
    '.....kk.kk......',
    '......kkk.......',
    '.......k........',
    '......kgk.......',
    '....nnn.nnn.....',
    '...n..n.n..n....',
    '..n...n.n...n...',
    '..n...n.n...n...',
    '..n..n...n..n...',
    '...nn.....nn....',
    '................',
  ],
  copy: [
    '................',
    'kkkkkk..........',
    'kwwwwkk.........',
    'kwkkkwwk........',
    'kwwwwwwk........',
    'kwkkkkkkkkkk....',
    'kwwwwkwwwwwkk...',
    'kwkkkkwkkkwkwk..',
    'kwwwwkwwwwwkkkk.',
    'kkkkkkwkkkkkwwk.',
    '.....kwwwwwwwwk.',
    '.....kwkkkkkkwk.',
    '.....kwwwwwwwwk.',
    '.....kwkkkkkkwk.',
    '.....kwwwwwwwwk.',
    '.....kkkkkkkkkk.',
  ],
  paste: [
    '................',
    '.....kkkk.......',
    '..kkkkllkkkk....',
    '.koookkkkooook..',
    '.kooooooooooook.',
    '.kooookkkkkkkk..',
    '.kooookwwwwwkwk.',
    '.kooookwkkkwkkkk',
    '.kooookwwwwwwwwk',
    '.kooookwkkkkkkwk',
    '.kooookwwwwwwwwk',
    '.kooookwkkkkkkwk',
    '.kooookwwwwwwwwk',
    '..kkkkkwwwwwwwwk',
    '......kkkkkkkkkk',
    '................',
  ],
  painter: [
    '................',
    '.kkkkkkkkkkk....',
    '.kyyyyyyyyykk...',
    '.kyyyyyyyyykwk..',
    '.kkkkkkkkkkkwk..',
    '..kwwwwwwwwwkk..',
    '...kkkkkkkkkk...',
    '.......kk.......',
    '.......kk.......',
    '......kgwk......',
    '......kgwk......',
    '......kgwk......',
    '......kgwk......',
    '......kkkk......',
    '................',
    '................',
  ],
  undo: [
    '................',
    '................',
    '................',
    '....k...........',
    '...kk...........',
    '..kbkkkkkkk.....',
    '.kbbbbbbbbbk....',
    '..kbkkkkkkbbk...',
    '...kk.....kbk...',
    '....k.....kbk...',
    '..........kbk...',
    '.........kbbk...',
    '.......kkbbk....',
    '.......kkkk.....',
    '................',
    '................',
  ],
  redo: [
    '................',
    '................',
    '................',
    '...........k....',
    '...........kk...',
    '.....kkkkkkkbk..',
    '....kbbbbbbbbbk.',
    '...kbbkkkkkkbk..',
    '...kbk.....kk...',
    '...kbk.....k....',
    '...kbk..........',
    '...kbbk.........',
    '....kbbkk.......',
    '.....kkkk.......',
    '................',
    '................',
  ],
  link: [
    '................',
    '.....kkkkk......',
    '...kkebbbbkk....',
    '..kbeeebbbbbk...',
    '..kbbeeebbbebk..',
    '.kbbbbeebbeeebk.',
    '.kbbbbbbbbeeebk.',
    '.kbbeebbbbbeebk.',
    '.kbeeeebbbbbbbk.',
    '.kbbeeeebkkkkkk.',
    '..kbbeebkwwwwwwk',
    '..kbbbbbkkkkkkkk',
    '...kkbbbbkwwwwwk',
    '.....kkkkkkkkkk.',
    '................',
    '................',
  ],
  sum: [
    '................',
    '..kkkkkkkkkk....',
    '..kk......kk....',
    '...kk.....k.....',
    '....kk..........',
    '.....kk.........',
    '......kk........',
    '.......kk.......',
    '......kk........',
    '.....kk.........',
    '....kk..........',
    '...kk.....k.....',
    '..kk......kk....',
    '..kkkkkkkkkk....',
    '................',
    '................',
  ],
  fx: [
    '................',
    '................',
    '.......kkk......',
    '......kk..k.....',
    '......k.........',
    '....kkkkk.......',
    '......k...k...k.',
    '.....kk....k.k..',
    '.....k......k...',
    '.....k.....k.k..',
    '....kk....k...k.',
    '....k...........',
    '..kk............',
    '................',
    '................',
    '................',
  ],
  sortAsc: [
    '................',
    '..kk.......k....',
    '.k..k......k....',
    '.kkkk......k....',
    '.k..k......k....',
    '.k..k......k....',
    '...........k....',
    '.kkkk......k....',
    '....k......k....',
    '...k.....kkkkk..',
    '..k.......kkk...',
    '.kkkk......k....',
    '................',
    '................',
    '................',
    '................',
  ],
  sortDesc: [
    '................',
    '.kkkk......k....',
    '....k......k....',
    '...k.......k....',
    '..k........k....',
    '.kkkk......k....',
    '...........k....',
    '..kk.......k....',
    '.k..k......k....',
    '.kkkk....kkkkk..',
    '.k..k.....kkk...',
    '.k..k......k....',
    '................',
    '................',
    '................',
    '................',
  ],
  chart: [
    '................',
    '................',
    '..........kkk...',
    '..........krk...',
    '......kkk.krk...',
    '......kbk.krk...',
    '..kkk.kbk.krk...',
    '..kyk.kbk.krk...',
    '..kyk.kbk.krk...',
    '..kyk.kbk.krk...',
    '..kyk.kbk.krk...',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  draw: [
    '................',
    '................',
    '.....kk.........',
    '....kyyk........',
    '...kyyyyk.......',
    '..kyyyyyyk......',
    '.kkkkkkkkkk.....',
    '..........kkkk..',
    '.........krrrrk.',
    '........krrrrrrk',
    '........krrrrrrk',
    '........krrrrrrk',
    '.........krrrrk.',
    '..........kkkk..',
    '................',
    '................',
  ],
  help: [
    '................',
    '.k..............',
    '.kk......kkkk...',
    '.kwk....kk..kk..',
    '.kwwk.......kk..',
    '.kwwwk.....kk...',
    '.kwwwwk...kk....',
    '.kwwwwwk..kk....',
    '.kwwkkkk........',
    '.kwk......kk....',
    '.kk.............',
    '.k..............',
    '................',
    '................',
    '................',
    '................',
  ],
  bold: [
    '................',
    '................',
    '...kkkkkkk......',
    '....kkk..kk.....',
    '....kkk..kk.....',
    '....kkk..kk.....',
    '....kkkkkk......',
    '....kkk..kkk....',
    '....kkk...kk....',
    '....kkk...kk....',
    '....kkk..kkk....',
    '...kkkkkkkk.....',
    '................',
    '................',
    '................',
    '................',
  ],
  italic: [
    '................',
    '................',
    '.......kkkkk....',
    '........kkk.....',
    '........kk......',
    '.......kkk......',
    '.......kk.......',
    '......kkk.......',
    '......kk........',
    '.....kkk........',
    '.....kk.........',
    '...kkkkk........',
    '................',
    '................',
    '................',
    '................',
  ],
  underline: [
    '................',
    '................',
    '...kkk...kkk....',
    '....k.....k.....',
    '....k.....k.....',
    '....k.....k.....',
    '....k.....k.....',
    '....k.....k.....',
    '....k.....k.....',
    '.....k...k......',
    '......kkk.......',
    '................',
    '...kkkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  alignLeft: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkk......',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkk......',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkk......',
    '................',
    '................',
    '................',
  ],
  alignCenter: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '....kkkkkkkk....',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '....kkkkkkkk....',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  alignRight: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '......kkkkkkkk..',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '......kkkkkkkk..',
    '................',
    '..kkkkkkkkkkkk..',
    '................',
    '......kkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  merge: [
    '................',
    'kkkkkkkkkkkkkkkk',
    'k..............k',
    'k..............k',
    'k..k........k..k',
    'k.kk..kkk...kk.k',
    'kkkkk....k.kkkkk',
    'k.kk...kkk..kk.k',
    'k..k..k..k..k..k',
    'k......kkk.....k',
    'k..............k',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
    '................',
  ],
  borders: [
    '................',
    '................',
    '.k.k.k.k.k.k.k..',
    '................',
    '.k.....k.....k..',
    '................',
    '.k.k.k.k.k.k.k..',
    '................',
    '.k.....k.....k..',
    '................',
    '.k.....k.....k..',
    '................',
    '.kkkkkkkkkkkkk..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
  ],
  fill: [
    '................',
    '......k.........',
    '.....kwk........',
    '....kwwwk.......',
    '...kwwwwwk......',
    '..kwwwwwwwk.....',
    '.kkwwwwwwwkkk...',
    '..kkwwwwwk.kk...',
    '...kkwwwk..kk...',
    '....kkwk...kk...',
    '.....kk.....k...',
    '................',
    '.yyyyyyyyyyyyy..',
    '.yyyyyyyyyyyyy..',
    '.yyyyyyyyyyyyy..',
    '................',
  ],
  fontColor: [
    '................',
    '......kk........',
    '.....kkkk.......',
    '.....k..k.......',
    '....kk..kk......',
    '....kkkkkk......',
    '...kk....kk.....',
    '...kk....kk.....',
    '..kkk....kkk....',
    '................',
    '................',
    '.rrrrrrrrrrrrr..',
    '.rrrrrrrrrrrrr..',
    '.rrrrrrrrrrrrr..',
    '................',
    '................',
  ],
  min: ['........', '........', '........', '........', '........', '........', 'kkkkkk..', 'kkkkkk..'],
  max: ['kkkkkkkkk', 'kkkkkkkkk', 'k.......k', 'k.......k', 'k.......k', 'k.......k', 'k.......k', 'k.......k', 'kkkkkkkkk'],
  restore: ['..kkkkkk', '..kkkkkk', '..k....k', 'kkkkkk.k', 'kkkkkk.k', 'k....kkk', 'k....k..', 'k....k..', 'kkkkkk..'],
  close: ['kk....kk', '.kk..kk.', '..kkkk..', '...kk...', '..kkkk..', '.kk..kk.', 'kk....kk'],
  arrowDown: ['kkkkkkk', '.kkkkk.', '..kkk..', '...k...'],
  arrowUp: ['...k...', '..kkk..', '.kkkkk.', 'kkkkkkk'],
  arrowLeft: ['...k', '..kk', '.kkk', 'kkkk', '.kkk', '..kk', '...k'],
  arrowRight: ['k...', 'kk..', 'kkk.', 'kkkk', 'kkk.', 'kk..', 'k...'],
  first: ['k...k', 'k..kk', 'k.kkk', 'kkkkk', 'k.kkk', 'k..kk', 'k...k'],
  last: ['k...k', 'kk..k', 'kkk.k', 'kkkkk', 'kkk.k', 'kk..k', 'k...k'],
  check: ['......k', '.....kk', 'k...kkk', 'kk.kkk.', 'kkkkk..', '.kkk...', '..k....'],
  cancel: ['kk...kk', '.kk.kk.', '..kkk..', '.kk.kk.', 'kk...kk'],
}

const cache = new Map<string, string>()

/** Inline SVG markup for a named pixel icon. */
export function icon(name: keyof typeof MAPS | string, scale = 1): string {
  const key = `${name}@${scale}`
  let svg = cache.get(key)
  if (!svg) {
    const map = MAPS[name]
    svg = map ? pixelSvg(map, scale) : ''
    cache.set(key, svg)
  }
  return svg
}

/** Toolbar 1 ("Standard"): icon names in order; '|' = separator, 'zoom' = zoom combo. */
export const STANDARD_TOOLBAR = [
  'new', 'open', 'save', '|', 'print', 'preview', 'spell', '|', 'cut', 'copy', 'paste', 'painter', '|',
  'undo', 'redo', '|', 'link', '|', 'sum', 'fx', 'sortAsc', 'sortDesc', '|', 'chart', 'draw', '|', 'zoom', '|', 'help',
]
