import { test, email, signIn, newPerson, openApp, wsEval, waitOnline, gotoPage, editorOf, createWorkspace, join, api } from './fixtures'

test('caret screenshots', async ({ page: a, context }) => {
  await signIn(a, email('ada'))
  await api(a, 'PATCH', '/api/me', { name: 'Ada Lovelace' })
  const wsId = await createWorkspace(a, 'Acme')
  await openApp(a, wsId)
  await waitOnline(a)
  const b = await newPerson(context)
  await signIn(b, email('bob'))
  await api(b, 'PATCH', '/api/me', { name: 'Bob' })
  await join(a, b, wsId)
  const id = await wsEval(a, (s) => s.createPage({ title: 'Launch plan' }))
  await gotoPage(a, id)
  await editorOf(a, id).click()
  await a.keyboard.type('We ship the new onboarding on Monday. Marketing has the copy ready; support needs the FAQ by Friday.')
  await a.keyboard.press('Enter')
  await a.keyboard.type('Open questions: pricing page, the press kit and who hosts the webinar.')
  await openApp(b, wsId, `/p/${id}`)
  await waitOnline(b)
  await editorOf(b, id).locator('p').first().click()
  await b.keyboard.press('End')
  await b.keyboard.type(' Bob checks the release notes.')
  await b.keyboard.press('Shift+Home')
  await a.waitForTimeout(600)
  await a.screenshot({ path: '.shots/caret-light.png' })
  await a.emulateMedia({ colorScheme: 'dark' })
  await a.evaluate(() => (window as any).__one.workspace.getState().updateSettings({ theme: 'dark' })) // eslint-disable-line
  await a.waitForTimeout(400)
  await a.screenshot({ path: '.shots/caret-dark.png' })
  await a.setViewportSize({ width: 390, height: 844 })
  await a.waitForTimeout(500)
  await a.screenshot({ path: '.shots/caret-mobile-dark.png' })
})
