#!/usr/bin/env python3
"""
Cuts the ~70-second promo: 1997 teaser → hammer → "what happens next?" card → feature tour → end card.

    python3 scripts/promo/assemble.py            # → public/media/simplecms-one.mp4 (served by the site)

Inputs (all generated by the other scripts in this folder, kept in .shots/promo):
  scenes/*.mp4         record-scenes.mjs      app clips, 1920×1080 / 30 fps (+ <scene>.json with its marks)
  teaser/*             record-teaser.mjs      1997 stills + hammer frames (hits at frames 20, 51, 84)
  cards/**             render-cards.mjs       captions, hook card, end-card states
  vo/l01..l10.mp3      text-to-speech lines + vo.json (word timestamps, faster-whisper)
The soundtrack is synthesised by music.py against the cue times computed here.
Needs Python 3 with numpy + scipy, and ffmpeg.
"""
import json
import os
import shutil
import subprocess
import sys
import wave

import numpy as np
from scipy.ndimage import maximum_filter1d

ROOT = '.shots/promo'
WORK = f'{ROOT}/build'
OUT = 'public/media/simplecms-one.mp4'
FPS = 30
SR = 48000
TEMPO = 1.1  # voice-over tempo
GRID = 0.25  # block cuts land on 8th notes of the 120 BPM groove
HITS = (20, 51, 84)  # teaser frames of the three hammer impacts (the last one whites out)
TEASER_FRAMES = 87

# Feature blocks: voice-over line and source windows (seconds into the scene clip, see the scene's
# marks in scenes/<name>.json). A clip with `at` starts when that word is spoken, so the picture follows
# the narration; speeds are fitted and clamped. `lead` starts the picture that long before the voice,
# `tail` holds it that long after the line (both seconds, default 0).
BLOCKS = [
    dict(line=3, clips=[dict(src='home', a=0.0, b=4.33)]),
    dict(line=4, clips=[dict(src='editor-a', a=0.2, b=4.8), dict(src='editor-b', a=0.6, b=4.9, at='toggles,'),
                        dict(src='forms', a=0.2, b=3.9, at='forms')]),
    dict(line=5, tail=1.0, clips=[dict(src='database', a=0.9, b=5.6), dict(src='database', a=6.2, b=9.9),
                                  dict(src='charts', a=0.0, b=5.6, at='charts')]),
    dict(line=6, tail=1.0, clips=[dict(src='sheets', a=0.2, b=8.3), dict(src='functions', a=0.3, b=1.33, at='own'),
                                  # skip the empty test bench's #DIV/0! — straight to the sample values
                                  dict(src='functions', a=2.83, b=6.0)]),
    dict(line=7, lead=1.0, clips=[dict(src='team', a=0.9, b=5.9), dict(src='team', a=6.4, b=8.6, at='private'),
                                  dict(src='team', a=8.9, b=11.2, at='every')]),
    dict(line=8, lead=1.0, clips=[dict(src='ai', a=3.6, b=8.0), dict(src='mcp', a=0.5, b=8.5, at='one')]),
    dict(line=9, lead=1.0, clips=[dict(src='meeting', a=1.4, b=5.3), dict(src='sync', a=0.6, b=3.0, at='sinks'),
                                  dict(src='automations', a=5.0, b=9.5, at='webhooks')]),
]
MAX_SPEED = 1.65
MIN_SPEED = 0.85
# Pauses longer than this are shortened (seconds); per-line overrides keyed by the pause start.
MAX_PAUSE = 0.25
PAUSE_OVERRIDES = {10: {0.98: 0.4, 3.28: 0.35, 5.88: 0.3}}


def sh(*args):
    subprocess.run(args, check=True)


def ffprobe_dur(path):
    return float(subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path]))


def decode(path):
    raw = subprocess.check_output(['ffmpeg', '-v', 'error', '-i', path, '-ac', '1', '-ar', str(SR), '-f', 'f32le', '-'])
    return np.frombuffer(raw, '<f4').astype(np.float64)


def write_wav(path, x):
    x = np.atleast_2d(x.T).T if x.ndim == 1 else x
    ch = 1 if x.ndim == 1 else x.shape[1]
    pcm = (np.clip(x, -1, 1) * 32767).astype('<i2')
    with wave.open(path, 'wb') as w:
        w.setnchannels(ch)
        w.setsampwidth(2)
        w.setframerate(SR)
        w.writeframes(pcm.tobytes())


# ------------------------------------------------------------------ voice-over
def silent_runs(x):
    hop = SR // 100
    n = len(x) // hop
    rms = np.sqrt((x[: n * hop].reshape(n, hop) ** 2).mean(1))
    db = 20 * np.log10(rms + 1e-9)
    sil = db < db.max() - 38
    runs, start = [], None
    for k, s in enumerate(list(sil) + [False]):
        if s and start is None:
            start = k
        elif not s and start is not None:
            if k - start >= 20:
                runs.append((start / 100, k / 100))
            start = None
    return runs


def process_line(i, words):
    """Shorten long pauses, trim the ends, speed up; returns audio + a time map for the words."""
    x = decode(f'{ROOT}/vo/l{i:02d}.mp3')
    dur = len(x) / SR
    runs = silent_runs(x)
    head = runs[0][1] - 0.03 if runs and runs[0][0] <= 0.01 else 0.0
    tail = runs[-1][0] + 0.12 if runs and runs[-1][1] >= dur - 0.02 else dur
    cuts = []  # (start, end) of removed audio
    for a, b in runs:
        if a <= 0.01 or b >= dur - 0.02:
            continue
        target = MAX_PAUSE
        for k, v in PAUSE_OVERRIDES.get(i, {}).items():
            if abs(a - k) < 0.08:
                target = v
        if b - a > target + 0.02:
            cuts.append((a + target / 2, b - target / 2))
    keep, pos = [], head
    for a, b in cuts:
        keep.append((pos, a))
        pos = b
    keep.append((pos, tail))
    xf = int(0.008 * SR)
    out = np.zeros(0)
    for a, b in keep:
        seg = x[int(a * SR) : int(b * SR)].copy()
        if len(out) and len(seg) > xf:
            ramp = np.linspace(0, 1, xf)
            out[-xf:] = out[-xf:] * (1 - ramp) + seg[:xf] * ramp
            seg = seg[xf:]
        out = np.concatenate([out, seg])

    def tmap(t):
        t = min(max(t, head), tail)
        removed = sum(b - a if t >= b else max(0.0, t - a) for a, b in cuts)
        return (t - head - removed) / TEMPO

    tmp = f'{WORK}/vo-l{i:02d}-cut.wav'
    write_wav(tmp, out)
    fin = f'{WORK}/vo-l{i:02d}.wav'
    sh('ffmpeg', '-v', 'error', '-y', '-i', tmp, '-af', f'atempo={TEMPO}', '-ar', str(SR), fin)
    y = decode(fin)
    ws = [dict(w=w['w'], s=tmap(w['s']), e=tmap(w['e'])) for w in words]
    return dict(audio=y, dur=len(y) / SR, words=ws)


def word_time(line, word, nth=0):
    hits = [w for w in line['words'] if w['w'].strip(',.').lower() == word.strip(',.').lower()]
    if len(hits) <= nth:
        raise SystemExit(f'word {word!r} not found in {[w["w"] for w in line["words"]]}')
    return hits[nth]['s']


# ------------------------------------------------------------------ video segments
class Cut:
    def __init__(self):
        self.segs = []  # (kind, frames, params)
        self.t = 0.0

    @property
    def frame(self):
        return round(self.t * FPS)

    def add(self, kind, until, **params):
        f0, f1 = self.frame, round(until * FPS)
        if f1 <= f0:
            raise SystemExit(f'empty segment {kind} {params}')
        self.segs.append((kind, f1 - f0, params))
        self.t = until


def render_segment(k, kind, frames, p):
    out = f'{WORK}/seg{k:03d}.mp4'
    enc = ['-r', str(FPS), '-frames:v', str(frames), '-an', '-c:v', 'libx264', '-crf', '15', '-preset', 'medium', '-pix_fmt', 'yuv420p', out]
    if kind == 'still':
        z0, z1 = p.get('zoom', (1.0, 1.0))
        z = f"{z0}+({z1}-{z0})*on/{max(1, frames - 1)}"
        vf = (f"scale=3840:2160:flags=lanczos,zoompan=z='{z}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)'"
              f":d=1:s=1920x1080:fps={FPS},format=yuv420p")
        sh('ffmpeg', '-v', 'error', '-y', '-framerate', str(FPS), '-loop', '1', '-i', p['img'], '-vf', vf, *enc)
    elif kind == 'frames':
        sh('ffmpeg', '-v', 'error', '-y', '-framerate', str(FPS), '-start_number', '0', '-i', p['pattern'],
           '-vf', 'scale=1920:1080:flags=lanczos,format=yuv420p', *enc)
    elif kind == 'clip':
        speed = p['speed']
        vf = (f"setpts=(PTS-STARTPTS)/{speed:.5f},fps={FPS},scale=1920:1080:flags=lanczos,"
              f"tpad=stop_mode=clone:stop_duration=5,format=yuv420p")
        sh('ffmpeg', '-v', 'error', '-y', '-ss', f"{p['a']:.3f}", '-to', f"{p['b']:.3f}", '-i', f"{ROOT}/scenes/{p['src']}.mp4",
           '-vf', vf, *enc)
    return out


def mix(vo, music, sections):
    """Voice on top; the music gets a per-section level and ducks (with look-ahead) under the voice."""
    n = min(len(vo), len(music))
    vo, music = vo[:n], music[:n]
    rate = 200  # envelope frames per second
    hop = SR // rate
    m = n // hop
    env = np.sqrt((vo[: m * hop].reshape(m, hop) ** 2).mean(1))
    act = (20 * np.log10(env + 1e-9) > -42).astype(float)
    act = maximum_filter1d(act, size=int(0.4 * rate))  # bridge word gaps, 0.2 s look-ahead
    sm = np.zeros(m)
    a_att, a_rel = np.exp(-1 / (0.06 * rate)), np.exp(-1 / (0.35 * rate))
    for k in range(1, m):
        c = a_att if act[k] > sm[k - 1] else a_rel
        sm[k] = c * sm[k - 1] + (1 - c) * act[k]
    t = np.arange(m) / rate
    level = np.zeros(m)
    depth = np.zeros(m)
    for start, lv, dp in sections:
        level[t >= start] = lv
        depth[t >= start] = dp
    # glide into each new level over 0.3 s so section changes do not click
    level = np.convolve(np.pad(level, (int(0.3 * rate), 0), mode='edge'), np.ones(int(0.3 * rate)) / int(0.3 * rate), 'valid')[:m]
    gain_db = level - depth * sm
    gain = np.interp(np.arange(n) / SR, t, 10 ** (gain_db / 20))
    out = music * gain[:, None] + vo[:, None] * 0.95
    return np.tanh(out / 0.92) * 0.92  # gentle soft limit; loudnorm sets the final level


def master(src, dst):
    """Two-pass EBU R128 normalisation to -14 LUFS / -2 dBTP (social video; AAC adds ~1 dB of overshoot)."""
    target = 'I=-14:TP=-2:LRA=11'
    hp = 'highpass=f=30'  # no sub-rumble below the kick
    log = subprocess.run(['ffmpeg', '-hide_banner', '-i', src, '-af', f'{hp},loudnorm={target}:print_format=json', '-f', 'null', '-'],
                         capture_output=True, text=True).stderr
    m = json.loads(log[log.rindex('{') : log.rindex('}') + 1])
    af = (f"{hp},loudnorm={target}:measured_I={m['input_i']}:measured_TP={m['input_tp']}:measured_LRA={m['input_lra']}"
          f":measured_thresh={m['input_thresh']}:offset={m['target_offset']}:linear=true,aresample={SR}")
    sh('ffmpeg', '-v', 'error', '-y', '-i', src, '-af', af, '-ar', str(SR), dst)


def snap(t, grid, base, mode='nearest'):
    k = (t - base) / grid
    k = {'nearest': round(k), 'ceil': np.ceil(k - 1e-6)}[mode]
    return base + k * grid


def main():
    os.makedirs(WORK, exist_ok=True)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    vo_words = json.load(open(f'{ROOT}/vo/vo.json'))
    L = {i: process_line(i, vo_words[f'l{i:02d}.mp3']['words']) for i in range(1, 11)}
    for i, l in L.items():
        print(f'L{i:02d} {l["dur"]:.2f}s')

    cut = Cut()
    vo_at = {}  # line → start time
    caps = []  # (caption index, t0, t1)

    # 1 — the 1997 homepage; it freezes on "costs", the hammer swings in, L2 lands on the first hit
    vo_at[1] = 0.2
    l1_end = vo_at[1] + L[1]['dur']
    hung = vo_at[1] + word_time(L[1], 'costs')
    S = l1_end + 0.2 + L[2]['dur'] - HITS[0] / FPS
    vo_at[2] = S + HITS[0] / FPS - L[2]['dur']
    zoom_rate = 0.05 / S
    cut.add('still', hung, img=f'{ROOT}/teaser/still-normal.png', zoom=(1.0, 1 + zoom_rate * hung))
    cut.add('still', S, img=f'{ROOT}/teaser/still-hung.png', zoom=(1 + zoom_rate * hung, 1.05))
    caps.append((1, vo_at[1] - 0.1, l1_end + 0.25))
    caps.append((2, vo_at[2] - 0.05, S + HITS[0] / FPS))
    cut.add('frames', S + TEASER_FRAMES / FPS, pattern=f'{ROOT}/teaser/smash/f%05d.png')
    hits = [S + h / FPS for h in HITS]

    # 2 — the spoiler-free card, a ticking clock, then the drop
    drop = cut.t + 1.85
    cut.add('still', drop, img=f'{ROOT}/cards/hook.png', zoom=(1.0, 1.025))

    # 3 — feature tour
    for bi, blk in enumerate(BLOCKS):
        line = L[blk['line']]
        t0 = cut.t
        v0 = t0 + 0.18 + blk.get('lead', 0.0)
        vo_at[blk['line']] = v0
        src_len = sum(c['b'] - c['a'] for c in blk['clips'])
        ms = blk.get('max_speed', MAX_SPEED)
        need = max(v0 - t0 + line['dur'] + 0.27 + blk.get('tail', 0.0), src_len / ms)
        t1 = snap(t0 + need, GRID, drop)
        if t1 < v0 + line['dur'] + 0.22 + blk.get('tail', 0.0):
            t1 += GRID
        if bi == len(BLOCKS) - 1:
            t1 = snap(t1, 0.5, drop, 'ceil')  # the end card starts on a beat
        # clip boundaries: anchored clips start at their word, the rest share the time evenly by length
        starts = [t0]
        for c in blk['clips'][1:]:
            starts.append(v0 + word_time(line, c['at']) - 0.15 if 'at' in c else None)
        bounds = starts + [t1]
        # fill un-anchored starts proportionally between anchored neighbours
        i = 0
        while i < len(bounds):
            if bounds[i] is None:
                j = i
                while bounds[j] is None:
                    j += 1
                seg = blk['clips'][i - 1 : j]
                total = sum(c['b'] - c['a'] for c in seg)
                acc = bounds[i - 1]
                for k in range(i, j):
                    c = blk['clips'][k - 1]
                    acc += (bounds[j] - bounds[i - 1]) * (c['b'] - c['a']) / total
                    bounds[k] = acc
                i = j
            i += 1
        for k, c in enumerate(blk['clips']):
            dur = bounds[k + 1] - bounds[k]
            speed = min(max((c['b'] - c['a']) / dur, MIN_SPEED), blk.get('max_speed', MAX_SPEED))
            b = min(c['b'], c['a'] + dur * speed)
            print(f"  {c['src']:12s} {c['a']:.2f}-{b:.2f}  {dur:.2f}s  x{speed:.2f}")
            cut.add('clip', bounds[k + 1], src=c['src'], a=c['a'], b=b, speed=speed)
        caps.append((blk['line'], v0 - 0.1, min(v0 + line['dur'] + 0.35 + blk.get('tail', 0.0), t1 - 0.05)))

    # 4 — end card: states follow the words ("No subscription." · "Your data stays yours."), the brand
    #     lands on a beat with the final hit
    endc = cut.t
    l10 = L[10]
    w_simple = word_time(l10, 'Simple')
    final = snap(endc + 0.15 + w_simple, 0.5, drop)
    if final - w_simple < endc + 0.08:
        final += 0.5
    vo_at[10] = final - w_simple
    marks = [endc, vo_at[10] + word_time(l10, 'your') - 0.05, final]
    end = vo_at[10] + l10['dur'] + 0.7
    for s in range(3):
        cut.add('still', marks[s + 1] if s < 2 else end, img=f'{ROOT}/cards/end-{s + 1}.png', zoom=(1.0, 1.0))
    total = cut.t
    print(f'drop {drop:.2f}  end card {endc:.2f}  final {final:.2f}  total {total:.2f}s')

    # ---- picture
    segs = []
    for k, (kind, frames, p) in enumerate(cut.segs):
        segs.append(render_segment(k, kind, frames, p))
    with open(f'{WORK}/concat.txt', 'w') as f:
        for s in segs:
            f.write(f"file '{os.path.abspath(s)}'\n")
    sh('ffmpeg', '-v', 'error', '-y', '-f', 'concat', '-safe', '0', '-i', f'{WORK}/concat.txt', '-c', 'copy', f'{WORK}/base.mp4')

    # ---- sound: voice-over track + synthesised music against the cues
    n = int((total + 0.5) * SR)
    vo = np.zeros(n)
    for i, t in vo_at.items():
        a = L[i]['audio']
        s = int(t * SR)
        vo[s : s + len(a)] += a[: n - s]
    cues = dict(length=total, hammer=S, hits=hits, drop=drop, end_card=endc, final=final)
    json.dump(cues, open(f'{WORK}/cues.json', 'w'), indent=1)
    sh(sys.executable, 'scripts/promo/music.py', f'{WORK}/cues.json', f'{WORK}/music.wav')
    with wave.open(f'{WORK}/music.wav') as w:
        music = np.frombuffer(w.readframes(w.getnframes()), '<i2').reshape(-1, 2) / 32768
    # music level (dB) and ducking depth (dB) per section: 1997 jingle, hammer + card, groove
    sections = [(0.0, 4.0, 5.0), (S, 0.0, 3.0), (drop, -7.8, 9.0)]
    write_wav(f'{WORK}/mix.wav', mix(vo, music, sections))
    master(f'{WORK}/mix.wav', f'{WORK}/master.wav')

    # ---- captions overlay + mix
    inputs = ['-i', f'{WORK}/base.mp4', '-i', f'{WORK}/master.wav']
    fc = []
    prev = '0:v'
    for j, (ci, a, b) in enumerate(caps):
        d = b - a
        inputs += ['-loop', '1', '-framerate', str(FPS), '-t', f'{d:.3f}', '-i', f'{ROOT}/cards/captions/cap-{ci:02d}.png']
        idx = 2 + j
        fc.append(f'[{idx}:v]format=rgba,fade=in:st=0:d=0.16:alpha=1,fade=out:st={d - 0.16:.3f}:d=0.16:alpha=1,'
                  f'setpts=PTS-STARTPTS+{a:.3f}/TB[c{j}]')
        x = f"'-36*max(0,1-(t-{a:.3f})/0.22)'"
        fc.append(f'[{prev}][c{j}]overlay=x={x}:y=0:eof_action=pass:enable=\'between(t,{a:.3f},{b:.3f})\'[v{j}]')
        prev = f'v{j}'
    fc.append(f'[{prev}]format=yuv420p[vout]')
    sh('ffmpeg', '-v', 'error', '-y', *inputs, '-filter_complex', ';'.join(fc), '-map', '[vout]', '-map', '1:a',
       '-t', f'{total:.3f}', '-c:v', 'libx264', '-crf', '18', '-preset', 'slow', '-profile:v', 'high', '-pix_fmt', 'yuv420p',
       '-movflags', '+faststart', '-c:a', 'aac', '-b:a', '192k', OUT)
    json.dump(dict(cues=cues, vo_at=vo_at, captions=caps), open(f'{WORK}/timeline.json', 'w'), indent=1)
    print('wrote', OUT, f'{ffprobe_dur(OUT):.2f}s')


if __name__ == '__main__':
    shutil.rmtree(WORK, ignore_errors=True)
    main()
