/**
 * The lucide glyphs a page icon can use ({ type: 'lucide', value: '<Name>' }) — a curated,
 * businesslike set, loaded on demand (PageIcon / the icon picker import this module lazily).
 * `de` holds German search words; the English ones come from the name itself.
 */
import {
  Archive,
  BadgeCheck,
  BarChart3,
  Bell,
  BookA,
  BookMarked,
  BookOpen,
  Bookmark,
  Boxes,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  ChartLine,
  CheckSquare,
  CircleDollarSign,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Compass,
  Contact,
  Cpu,
  Database,
  FileText,
  Files,
  Flag,
  FlaskConical,
  Folder,
  FolderKanban,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Home,
  Inbox,
  Landmark,
  Layers,
  LayoutDashboard,
  Library,
  Lightbulb,
  Link,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageSquare,
  Mic,
  Milestone,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  PenTool,
  PieChart,
  Plane,
  Presentation,
  Receipt,
  Rocket,
  Ruler,
  Scale,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sparkle,
  Star,
  Target,
  Terminal,
  Timer,
  Trophy,
  Truck,
  Users,
  Wallet,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export interface LucideEntry {
  name: string
  Icon: LucideIcon
  de: string
}

const e = (name: string, Icon: LucideIcon, de: string): LucideEntry => ({ name, Icon, de })

export const LUCIDE_ICONS: LucideEntry[] = [
  e('FileText', FileText, 'dokument seite text'),
  e('Files', Files, 'dateien dokumente'),
  e('BookOpen', BookOpen, 'buch wiki handbuch'),
  e('Library', Library, 'bibliothek leseliste'),
  e('BookA', BookA, 'glossar wörterbuch'),
  e('BookMarked', BookMarked, 'lesezeichen buch'),
  e('NotebookPen', NotebookPen, 'notizbuch notizen protokoll'),
  e('ClipboardList', ClipboardList, 'klemmbrett liste'),
  e('ListChecks', ListChecks, 'checkliste aufgaben'),
  e('ListTodo', ListTodo, 'todo aufgaben'),
  e('CheckSquare', CheckSquare, 'erledigt haken'),
  e('Calendar', Calendar, 'kalender datum'),
  e('CalendarDays', CalendarDays, 'kalender woche termine'),
  e('Clock', Clock, 'uhr zeit'),
  e('Timer', Timer, 'stoppuhr zeit'),
  e('Milestone', Milestone, 'meilenstein wegweiser'),
  e('Flag', Flag, 'flagge ziel start'),
  e('Target', Target, 'ziel okr fokus'),
  e('Trophy', Trophy, 'pokal erfolg'),
  e('Rocket', Rocket, 'rakete start launch'),
  e('FolderKanban', FolderKanban, 'projekte board ordner'),
  e('Folder', Folder, 'ordner'),
  e('Archive', Archive, 'archiv'),
  e('Inbox', Inbox, 'eingang posteingang'),
  e('LayoutDashboard', LayoutDashboard, 'dashboard übersicht'),
  e('Layers', Layers, 'ebenen schichten'),
  e('Boxes', Boxes, 'kisten module'),
  e('Package', Package, 'paket produkt'),
  e('Database', Database, 'datenbank daten'),
  e('BarChart3', BarChart3, 'diagramm statistik balken'),
  e('ChartLine', ChartLine, 'diagramm kurve wachstum'),
  e('PieChart', PieChart, 'kuchendiagramm anteile'),
  e('Gauge', Gauge, 'messgerät tacho kennzahl'),
  e('Ruler', Ruler, 'lineal messen'),
  e('Calculator', Calculator, 'rechner budget'),
  e('Receipt', Receipt, 'rechnung beleg'),
  e('Wallet', Wallet, 'geldbörse finanzen'),
  e('CircleDollarSign', CircleDollarSign, 'geld dollar umsatz'),
  e('Landmark', Landmark, 'bank behörde'),
  e('Scale', Scale, 'waage recht vertrag'),
  e('Briefcase', Briefcase, 'aktenkoffer arbeit job'),
  e('Building2', Building2, 'gebäude firma büro'),
  e('Handshake', Handshake, 'handschlag partner kunde'),
  e('Users', Users, 'team personen leute'),
  e('Contact', Contact, 'kontakt crm'),
  e('Mail', Mail, 'mail post nachricht'),
  e('MessageSquare', MessageSquare, 'nachricht kommentar chat'),
  e('Megaphone', Megaphone, 'megafon marketing ankündigung'),
  e('Mic', Mic, 'mikrofon podcast stimme'),
  e('Newspaper', Newspaper, 'zeitung news presse'),
  e('Presentation', Presentation, 'präsentation vortrag'),
  e('Palette', Palette, 'palette design farbe'),
  e('PenTool', PenTool, 'stift design'),
  e('Lightbulb', Lightbulb, 'glühbirne idee'),
  e('Brain', Brain, 'gehirn wissen'),
  e('GraduationCap', GraduationCap, 'lernen schulung kurs'),
  e('FlaskConical', FlaskConical, 'labor experiment test'),
  e('Compass', Compass, 'kompass onboarding orientierung'),
  e('Map', Map, 'karte roadmap'),
  e('Globe', Globe, 'welt website international'),
  e('Plane', Plane, 'flugzeug reise'),
  e('Truck', Truck, 'lkw lieferung logistik'),
  e('ShoppingCart', ShoppingCart, 'einkauf shop'),
  e('Gift', Gift, 'geschenk'),
  e('Home', Home, 'haus start'),
  e('Code2', Code2, 'code entwicklung'),
  e('Terminal', Terminal, 'terminal konsole'),
  e('Cpu', Cpu, 'prozessor technik'),
  e('Cloud', Cloud, 'wolke cloud'),
  e('Bug', Bug, 'fehler bug'),
  e('Workflow', Workflow, 'ablauf prozess automation'),
  e('Zap', Zap, 'blitz automation schnell'),
  e('Wrench', Wrench, 'werkzeug tools'),
  e('Settings', Settings, 'einstellungen zahnrad'),
  e('Shield', Shield, 'schild sicherheit'),
  e('Lock', Lock, 'schloss privat'),
  e('BadgeCheck', BadgeCheck, 'geprüft qualität'),
  e('Link', Link, 'link verknüpfung'),
  e('Search', Search, 'suche lupe'),
  e('Bell', Bell, 'glocke erinnerung'),
  e('Bookmark', Bookmark, 'lesezeichen'),
  e('Star', Star, 'stern favorit'),
  e('Heart', Heart, 'herz'),
  e('Sparkle', Sparkle, 'funke highlight'),
]

export const LUCIDE_BY_NAME: Record<string, LucideIcon> = Object.fromEntries(LUCIDE_ICONS.map((x) => [x.name, x.Icon]))

/** "CalendarDays" → "calendar days" (English search words). */
export const lucideWords = (name: string) => name.replace(/([a-z])([A-Z0-9])/g, '$1 $2').toLowerCase()
