import { chromium } from 'playwright'
const browser = await chromium.launch()
const ctx = await browser.newContext({ locale: 'en-US' })
await ctx.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://127.0.0.1:5403' })
const page = await ctx.newPage()
await page.goto('http://127.0.0.1:5403/app/?e2e')
await page.waitForFunction(() => !!window.__one, null, { timeout: 30000 })
const id = await page.evaluate(() => { const s = window.__one.workspace.getState(); const id = s.createPage({ title: 'Dbg' }); s.setContent(id, { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'Row notes' }] }, { type: 'button', attrs: { label: 'Hello', variant: 'ink', actions: [{ id: 'm', type: 'message', text: 'MSG shown' }, { id: 'w', type: 'webhook', url: 'https://x.test/h', method: 'POST' }] } }, { type: 'paragraph' }] }, 'x'); return id })
await page.evaluate((id) => (window.location.hash = `#/p/${id}`), id)
await page.waitForTimeout(800)
const ed = page.locator('#main .pv-content .ProseMirror')
await ed.locator('p').last().click()
await page.keyboard.press('ArrowUp')
await page.keyboard.press('Control+c')
await ed.locator('p').last().click()
await page.keyboard.press('Control+v')
await page.waitForTimeout(800)
const buttons = await page.evaluate((id) => window.__one.workspace.getState().pages[id].content.content.filter((n) => n.type === 'button').map((n) => n.attrs), id)
console.log(JSON.stringify(buttons))
await browser.close()
