/**
 * The vault: this browser profile's secrets (the Claude API key, the GitHub sync token), encrypted
 * at rest with WebCrypto. No home-made crypto, no passphrase to remember.
 *
 *  - One AES-GCM key (256 bit) per browser profile, generated by WebCrypto as NON-EXTRACTABLE and
 *    kept in IndexedDB (`one-vault` / `kv`, record "key"). IndexedDB stores the CryptoKey object
 *    itself: its bytes are never visible to JavaScript and never part of a storage file anyone can
 *    copy and read, a backup, an export or a sync — pages of this origin can only USE it, through
 *    crypto.subtle.
 *  - A secret: record "s:<scope>|<name>" → { v: 1, iv: 12 random bytes (fresh per seal), data:
 *    ciphertext + GCM tag, hint: its last 4 characters, at }. AAD = "one-vault/1\n<scope>\n<name>",
 *    so a sealed value copied to another name or workspace does not open.
 *  - Scope: the workspace a secret belongs to ("local:local", "cloud:<id>").
 *  - Callers keep a MARKER where the plaintext used to be ("vault:<seal id>:<last 4>"): enough to
 *    say "a key is set" synchronously and to show "•••• 1a2B", useless to anyone who reads it.
 *  - Writes take the Web Lock "one-vault" exclusively, reads share it: a tab that reads right after
 *    another tab sealed (and stored the marker) waits for that seal to land.
 *
 * What this protects against, and what not: docs/SECURITY.md.
 */
import { createStore, del, delMany, get, keys, set, type UseStore } from 'idb-keyval'
import { newId } from './ids'

const DB = 'one-vault'
const KEY_RECORD = 'key'
const PREFIX = 's:'
const LOCK = 'one-vault'
const AAD_TAG = 'one-vault/1'

interface Sealed {
  v: 1
  iv: Uint8Array<ArrayBuffer>
  data: ArrayBuffer
  /** last 4 characters ('' for short secrets) — what the UI shows anyway */
  hint: string
  at: number
}

/** WebCrypto and IndexedDB are there (a secure context: https or localhost). */
export function vaultAvailable(): boolean {
  return (
    typeof indexedDB !== 'undefined' &&
    typeof crypto !== 'undefined' &&
    !!crypto.subtle &&
    (typeof isSecureContext === 'undefined' || isSecureContext)
  )
}

let kv: UseStore | null = null
function db(): UseStore {
  if (!vaultAvailable()) throw new Error('vault unavailable: needs WebCrypto and IndexedDB (https)')
  return (kv ??= createStore(DB, 'kv'))
}

function withLock<T>(mode: LockMode, fn: () => Promise<T>): Promise<T> {
  const locks = typeof navigator !== 'undefined' ? navigator.locks : undefined
  return locks?.request ? (locks.request(LOCK, { mode }, fn) as Promise<T>) : fn()
}

/* ------------------------------------------------------------------ */
/* The profile key                                                     */
/* ------------------------------------------------------------------ */

let keyP: Promise<CryptoKey> | null = null
function profileKey(): Promise<CryptoKey> {
  keyP ??= loadOrCreateKey().catch((e) => {
    keyP = null
    throw e
  })
  return keyP
}

async function loadOrCreateKey(): Promise<CryptoKey> {
  const store = db()
  const existing = await get<unknown>(KEY_RECORD, store)
  if (existing instanceof CryptoKey) return existing
  const fresh = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt'])
  // another tab may have stored one meanwhile: the first one stays (one read-write transaction)
  return store(
    'readwrite',
    (os) =>
      new Promise<CryptoKey>((resolve, reject) => {
        let out = fresh
        const req = os.get(KEY_RECORD)
        req.onsuccess = () => {
          if (req.result instanceof CryptoKey) out = req.result
          else os.put(fresh, KEY_RECORD)
        }
        os.transaction.oncomplete = () => resolve(out)
        os.transaction.onerror = os.transaction.onabort = () => reject(os.transaction.error ?? new Error('vault: the key was not stored'))
      }),
  )
}

/* ------------------------------------------------------------------ */
/* Secrets                                                             */
/* ------------------------------------------------------------------ */

const recordKey = (name: string, scope: string) => `${PREFIX}${scope}|${name}`
const aad = (name: string, scope: string) => new TextEncoder().encode(`${AAD_TAG}\n${scope}\n${name}`)

/** The last 4 characters of a secret, for "•••• 1a2B" ('' when it is too short to show any). */
export function hintOf(secret: string): string {
  const s = secret.trim()
  return s.length >= 12 ? s.slice(-4) : ''
}

/**
 * Encrypt `plaintext` and store it as `name` of `scope` (replacing what was there). The lock is
 * requested synchronously, so a marker stored right after this call is never read before the seal.
 */
export function sealSecret(name: string, plaintext: string, scope: string): Promise<void> {
  return withLock('exclusive', async () => {
    const store = db()
    const key = await profileKey()
    const iv = crypto.getRandomValues(new Uint8Array(12))
    const data = await crypto.subtle.encrypt({ name: 'AES-GCM', iv, additionalData: aad(name, scope) }, key, new TextEncoder().encode(plaintext))
    const rec: Sealed = { v: 1, iv, data, hint: hintOf(plaintext), at: Date.now() }
    await set(recordKey(name, scope), rec, store)
  })
}

/** The secret `name` of `scope`, decrypted — null when there is none (or it can't be opened here). */
export function openSecret(name: string, scope: string): Promise<string | null> {
  if (!vaultAvailable()) return Promise.resolve(null)
  return withLock('shared', async () => {
    const store = db()
    const rec = await get<Sealed>(recordKey(name, scope), store)
    if (!rec || rec.v !== 1 || !(rec.iv instanceof Uint8Array) || !(rec.data instanceof ArrayBuffer)) return null
    try {
      const key = await profileKey()
      const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: rec.iv, additionalData: aad(name, scope) }, key, rec.data)
      return new TextDecoder().decode(plain)
    } catch {
      // never log anything of the secret itself
      console.warn(`[one] vault: "${name}" could not be decrypted here — it has to be entered again`)
      return null
    }
  })
}

/** Remove the secret `name` of `scope`. */
export function clearSecret(name: string, scope: string): Promise<void> {
  if (!vaultAvailable()) return Promise.resolve()
  return withLock('exclusive', () => del(recordKey(name, scope), db()))
}

/** Remove every secret whose scope `match` accepts (a team workspace's copy leaves this browser). */
export function clearSecrets(match: (scope: string) => boolean): Promise<void> {
  if (!vaultAvailable()) return Promise.resolve()
  return withLock('exclusive', async () => {
    const store = db()
    const drop = (await keys(store)).map(String).filter((k) => k.startsWith(PREFIX) && match(k.slice(PREFIX.length, k.indexOf('|'))))
    if (drop.length) await delMany(drop, store)
  })
}

/* ------------------------------------------------------------------ */
/* Markers                                                             */
/* ------------------------------------------------------------------ */

const MARKER_RE = /^vault:([0-9a-z]{6,24}):([\s\S]{0,4})$/

/** A marker for a secret about to be sealed: a fresh seal id + its last 4 characters. */
export function newSecretMarker(plaintext: string): string {
  return `vault:${newId()}:${hintOf(plaintext)}`
}

export function isSecretMarker(v: unknown): v is string {
  return typeof v === 'string' && MARKER_RE.test(v)
}

/** The last 4 characters a marker shows ('' for none). */
export function markerHint(marker: string): string {
  return MARKER_RE.exec(marker)?.[2] ?? ''
}
